[package]
name = "mdx-discover"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
topcoat = { workspace = true, features = ["mdx", "serve", "view", "router", "discover"] }
topcoat-mdx = { workspace = true, features = ["discover"] }

[lints]
workspace = true
